services:
  postgres:
    image: postgres:16
    container_name: postgres-n8n-compose
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: n8n_queue
    volumes:
      - db_storage:/var/lib/postgresql/data
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U postgres -d n8n_queue"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      internal:
        aliases:
          - postgres-n8n
    labels:
      - "traefik.enable=false"

  redis:
    image: redis:6-alpine
    container_name: redis-n8n-compose
    restart: always
    volumes:
      - redis_storage:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      internal:
        aliases:
          - redis-n8n
    labels:
      - "traefik.enable=false"

  n8n_editor:
    image: n8nio/n8n:latest
    container_name: n8n_editor
    restart: always
    ports:
      - 5678:5678
    environment:
      # Configurações do banco de dados
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres-n8n
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n_queue
      - DB_POSTGRESDB_USER=postgres
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
      # Configurações do Redis e filas
      - EXECUTIONS_MODE=queue
      - QUEUE_BULL_REDIS_HOST=redis-n8n
      - QUEUE_BULL_REDIS_PORT=6379
      - QUEUE_BULL_REDIS_DB=1
      - QUEUE_HEALTH_CHECK_ACTIVE=true
      # Configurações gerais
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_TRUSTED_PROXIES=*
      - N8N_TRUST_PROXY=true
      - N8N_METRICS=true
      - N8N_METRICS_INCLUDE_QUEUE_METRICS=true
      - N8N_PORT=5678
      - N8N_HOST=workflows.nooknerd.com.br
      - N8N_EDITOR_BASE_URL=https://workflows.nooknerd.com.br/
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://webhook.nooknerd.com.br/
      - N8N_ENDPOINT_WEBHOOK=webhook
      - N8N_PUSH_BACKEND=websocket
      - N8N_RUNNERS_ENABLED=false
      - N8N_RUNNERS_MODE=internal
      - OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS=false
      - GENERIC_TIMEZONE=America/Sao_Paulo
      # Configurações de execuções
      - EXECUTIONS_TIMEOUT=3600
      - EXECUTIONS_TIMEOUT_MAX=7200
      # Configurações de limpeza
      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_MAX_AGE=336
      - EXECUTIONS_DATA_PRUNE_HARD_DELETE_INTERVAL=15
      - EXECUTIONS_DATA_PRUNE_SOFT_DELETE_INTERVAL=60
      - EXECUTIONS_DATA_PRUNE_MAX_COUNT=10000
      - EXECUTIONS_DATA_SAVE_ON_ERROR=all
      - EXECUTIONS_DATA_SAVE_ON_SUCCESS=all
      - EXECUTIONS_DATA_SAVE_ON_PROGRESS=true
      - EXECUTIONS_DATA_SAVE_MANUAL_EXECUTIONS=true
      # Configurações de bibliotecas e nodes
      - NODE_FUNCTION_ALLOW_BUILTIN=*
      - NODE_FUNCTION_ALLOW_EXTERNAL=lodash
      - N8N_COMMUNITY_PACKAGES_ENABLED=true
      - N8N_REINSTALL_MISSING_PACKAGES=true
      - N8N_NODE_PATH=/home/node/.n8n/nodes
    volumes:
      - n8n_storage:/home/node/.n8n
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - web
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.rule=Host(`workflows.nooknerd.com.br`)"
      - "traefik.http.routers.n8n.tls=true"
      - "traefik.http.routers.n8n.tls.certresolver=lets-encrypt"
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"
      - "traefik.docker.network=web"

  n8n-webhook:
    image: n8nio/n8n:latest
    container_name: n8n-compose-webhook
    restart: always
    command: webhook
    environment:
      # Configurações do banco de dados
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres-n8n
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n_queue
      - DB_POSTGRESDB_USER=postgres
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
      # Configurações do Redis e filas
      - EXECUTIONS_MODE=queue
      - QUEUE_BULL_REDIS_HOST=redis-n8n
      - QUEUE_BULL_REDIS_PORT=6379
      - QUEUE_BULL_REDIS_DB=1
      - QUEUE_HEALTH_CHECK_ACTIVE=true
      # Configurações gerais
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_TRUSTED_PROXIES=*
      - N8N_TRUST_PROXY=true
      - N8N_METRICS=true
      - N8N_METRICS_INCLUDE_QUEUE_METRICS=true
      - N8N_PORT=5678
      - N8N_HOST=webhook.nooknerd.com.br
      - N8N_EDITOR_BASE_URL=https://workflows.nooknerd.com.br/
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://webhook.nooknerd.com.br/
      - N8N_WEBHOOK_URL=https://webhook.nooknerd.com.br/
      - N8N_ENDPOINT_WEBHOOK=webhook
      - N8N_PUSH_BACKEND=websocket
      - N8N_RUNNERS_ENABLED=false
      - N8N_RUNNERS_MODE=internal
      - OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS=false
      - GENERIC_TIMEZONE=America/Sao_Paulo
      # Configurações de execuções
      - EXECUTIONS_TIMEOUT=3600
      - EXECUTIONS_TIMEOUT_MAX=7200
      # Configurações de limpeza
      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_MAX_AGE=336
      - EXECUTIONS_DATA_PRUNE_HARD_DELETE_INTERVAL=15
      - EXECUTIONS_DATA_PRUNE_SOFT_DELETE_INTERVAL=60
      - EXECUTIONS_DATA_PRUNE_MAX_COUNT=10000
      - EXECUTIONS_DATA_SAVE_ON_ERROR=all
      - EXECUTIONS_DATA_SAVE_ON_SUCCESS=all
      - EXECUTIONS_DATA_SAVE_ON_PROGRESS=true
      - EXECUTIONS_DATA_SAVE_MANUAL_EXECUTIONS=true
      # Configurações de bibliotecas e nodes
      - NODE_FUNCTION_ALLOW_BUILTIN=*
      - NODE_FUNCTION_ALLOW_EXTERNAL=lodash
      - N8N_COMMUNITY_PACKAGES_ENABLED=true
      - N8N_REINSTALL_MISSING_PACKAGES=true
      - N8N_NODE_PATH=/home/node/.n8n/nodes
    volumes:
      - n8n_storage:/home/node/.n8n
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - web
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n-webhook.rule=Host(`webhook.nooknerd.com.br`)"
      - "traefik.http.middlewares.webhook-prefix.stripprefix.prefixes=/webhook"
      - "traefik.http.routers.n8n-webhook-test.rule=Host(`webhook.nooknerd.com.br`) && PathPrefix(`/webhook-test`)"
      - "traefik.http.middlewares.webhook-test-prefix.stripprefix.prefixes=/webhook-test"
      - "traefik.http.routers.n8n-webhook.tls=true"
      - "traefik.http.routers.n8n-webhook.tls.certresolver=lets-encrypt"
      - "traefik.http.routers.n8n-webhook-test.tls=true"
      - "traefik.http.routers.n8n-webhook-test.tls.certresolver=lets-encrypt"
      - "traefik.http.services.n8n-webhook.loadbalancer.server.port=5678"
      - "traefik.docker.network=web"
      
  n8n-worker:
    image: n8nio/n8n:latest
    container_name: n8n-compose-worker
    restart: always
    command: worker
    environment:
      # Configurações do banco de dados
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres-n8n
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n_queue
      - DB_POSTGRESDB_USER=postgres
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
      # Configurações do Redis e filas
      - EXECUTIONS_MODE=queue
      - QUEUE_BULL_REDIS_HOST=redis-n8n
      - QUEUE_BULL_REDIS_PORT=6379
      - QUEUE_BULL_REDIS_DB=1
      - QUEUE_HEALTH_CHECK_ACTIVE=true
      - QUEUE_WORKER_CONCURRENCY=${QUEUE_WORKER_CONCURRENCY:-5}
      # Configurações gerais
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_TRUSTED_PROXIES=*
      - N8N_TRUST_PROXY=true
      - N8N_METRICS=true
      - N8N_METRICS_INCLUDE_QUEUE_METRICS=true
      - N8N_PORT=5678
      - N8N_HOST=workflows.nooknerd.com.br
      - N8N_EDITOR_BASE_URL=https://workflows.nooknerd.com.br/
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://webhook.nooknerd.com.br/
      - N8N_WEBHOOK_URL=https://webhook.nooknerd.com.br/
      - N8N_ENDPOINT_WEBHOOK=webhook
      - N8N_PUSH_BACKEND=websocket
      - N8N_RUNNERS_ENABLED=false
      - N8N_RUNNERS_MODE=internal
      - OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS=false
      - GENERIC_TIMEZONE=America/Sao_Paulo
      # Configurações de execuções
      - EXECUTIONS_TIMEOUT=3600
      - EXECUTIONS_TIMEOUT_MAX=7200
      # Configurações de limpeza
      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_MAX_AGE=336
      - EXECUTIONS_DATA_PRUNE_HARD_DELETE_INTERVAL=15
      - EXECUTIONS_DATA_PRUNE_SOFT_DELETE_INTERVAL=60
      - EXECUTIONS_DATA_PRUNE_MAX_COUNT=10000
      - EXECUTIONS_DATA_SAVE_ON_ERROR=all
      - EXECUTIONS_DATA_SAVE_ON_SUCCESS=all
      - EXECUTIONS_DATA_SAVE_ON_PROGRESS=true
      - EXECUTIONS_DATA_SAVE_MANUAL_EXECUTIONS=true
      # Configurações de bibliotecas e nodes
      - NODE_FUNCTION_ALLOW_BUILTIN=*
      - NODE_FUNCTION_ALLOW_EXTERNAL=lodash
      - N8N_COMMUNITY_PACKAGES_ENABLED=true
      - N8N_REINSTALL_MISSING_PACKAGES=true
      - N8N_NODE_PATH=/home/node/.n8n/nodes
    volumes:
      - n8n_storage:/home/node/.n8n
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - internal
    labels:
      - "traefik.enable=false"

networks:
  web:
    external: true
  internal:
    driver: bridge

volumes:
  db_storage:
  n8n_storage:
  redis_storage: